import type { Metadata } from "next";

const companyName = "SAFWE ENERGY SOLUTIONS PRIVATE LIMITED";
const policyTitle = "SOLAR COMPARE BY SAFWE ENERGY SOLUTIONS PRIVATE LIMITED";

export const metadata: Metadata = {
  title: policyTitle,
  description: `Privacy Policy for Solar Compare, operated by ${companyName}.`,
};

type PolicySection = {
  title: string;
  paragraphs: string[];
  items?: string[];
};

const sections: PolicySection[] = [
  {
    title: "Introduction",
    paragraphs: [
      `Solar Compare is operated by ${companyName}. We help homeowners and businesses in India compare solar options, understand project considerations, use calculators, and connect with solar service providers. This Privacy Policy explains how information is handled when you use the Solar Compare website, account features, forms, calculators, and related services.`,
      "By using the website, you acknowledge the practices described here. Where a feature asks for information, we will use that information for the purpose explained at the point of collection or as described in this policy.",
    ],
  },
  {
    title: "Information We Collect",
    paragraphs: [
      "The information we handle depends on how you use Solar Compare. It may include information you provide directly, information generated by your use of account and comparison features, and operational information associated with requests submitted through the website.",
    ],
  },
  {
    title: "Information You Provide",
    paragraphs: [
      "You may provide information when you create or use an account, apply as a vendor, request a consultation or quotation, submit a contact inquiry, use a service inquiry form, or communicate with us.",
    ],
    items: [
      "Account details such as your name, email address, password, phone number, city, state, and pincode.",
      "Vendor details such as business and owner information, contact details, service areas, business type, experience, services, optional GST information, and submitted documents or images.",
      "Project and enquiry details such as your location, service requirement, monthly bill or roof information where requested, message, notes, and communication preferences.",
      "Referral information when you use or provide a referral code.",
    ],
  },
  {
    title: "Information Collected Automatically",
    paragraphs: [
      "The website may create operational records such as account activity, sign-in time, verification and password-reset token status, notifications, enquiry status, calculator history for signed-in users, and audit records used to operate and protect the service. The website also uses browser storage for authentication/session information and features such as saved vendors, selected comparison vendors, guest lead-capture state, and an AI chat conversation identifier.",
      "The site stores your selected language preference in a browser cookie. This policy does not assume that advertising cookies or cross-site tracking are used; if that changes, this policy will be updated.",
    ],
  },
  {
    title: "How We Use Your Information",
    paragraphs: [
      "We use information to provide and maintain Solar Compare features, including account access, email verification, password recovery, comparison and calculator features, quote or consultation requests, vendor applications, notifications, and responses to contact enquiries.",
      "We also use it to route a request to the relevant internal team or approved vendor, review vendor applications, maintain service and security records, prevent misuse, troubleshoot issues, and communicate about a request or account. We do not use information for a purpose that is incompatible with the context in which it was collected.",
    ],
  },
  {
    title: "How We Share Information",
    paragraphs: [
      "Solar Compare shares information only as needed to operate the requested feature. For example, details submitted in a vendor enquiry or consultation request may be made available to the relevant approved vendor and to our internal administration team so the request can be reviewed and followed up.",
      "We may also share information with service providers that help us deliver communications, hosting, database, security, or other technical functions. We do not claim that personal information is sold. We may disclose information where required to comply with a lawful request, protect the service, or address fraud, security, or safety concerns.",
    ],
  },
  {
    title: "Vendor / Partner Information",
    paragraphs: [
      "Vendor applications may include business, owner, service-area, contact, experience, service, and document information. This information is reviewed by Solar Compare administrators as part of the vendor workflow. Information about approved vendors may be shown to users as part of the comparison and connection experience. Vendors are responsible for the accuracy of information they submit and for handling information they receive through a customer request in accordance with applicable requirements.",
    ],
  },
  {
    title: "Cookies and Similar Technologies",
    paragraphs: [
      "Solar Compare currently uses a cookie to remember the selected site language. It also uses browser local storage for certain account, comparison, saved-item, calculator, and chat states. You can clear or restrict browser storage through your browser settings, although doing so may affect sign-in and saved features. The application does not represent that every third-party link or service uses the same storage practices.",
    ],
  },
  {
    title: "Communications and Notifications",
    paragraphs: [
      "We may send transactional communications such as email verification codes, password-reset messages, welcome or account messages, and updates related to a request or vendor workflow. The application also provides account notifications. These communications are part of providing the requested service. Where a message is not necessary for the requested service, you may contact us about your communication preferences.",
    ],
  },
  {
    title: "Data Security",
    paragraphs: [
      "We use measures appropriate to the application, including authenticated access, password hashing, expiring verification and password-reset tokens, role-based access controls, audit records, and restricted administrative workflows. No internet transmission or storage system can be guaranteed to be completely secure, so please use a unique password and contact us promptly if you believe your account has been accessed without permission.",
    ],
  },
  {
    title: "Data Retention",
    paragraphs: [
      "We retain information for as long as reasonably necessary to provide the relevant feature, manage an account or request, maintain operational and security records, resolve disputes, and meet applicable legal or accounting needs. Retention can vary by record type and is not necessarily the same for account data, enquiry data, tokens, uploaded documents, notifications, or audit records. When information is no longer needed, it may be deleted, anonymised, or securely disposed of in accordance with our operational processes.",
    ],
  },
  {
    title: "User Rights and Choices",
    paragraphs: [
      "You may request access to, correction of, or clarification about personal information associated with your Solar Compare account or enquiry. You may also ask us to consider deletion or restriction of information where applicable, subject to records we need to retain for security, legal, or operational purposes. You can manage local browser storage through your browser settings and can stop using a feature or contact us about a specific request.",
    ],
  },
  {
    title: "Third-Party Services and Links",
    paragraphs: [
      "Solar Compare may link to social networks, external websites, or services used to support website operations and communications. Those third parties have their own privacy policies and terms. This policy applies to Solar Compare's handling of information, not to the practices of websites you visit through an external link.",
    ],
  },
  {
    title: "Children's Privacy",
    paragraphs: [
      "Solar Compare is intended for adults and businesses making solar-related decisions. We do not knowingly request personal information from children. If you believe a child has provided information to us, please contact us so we can review the request and take appropriate action.",
    ],
  },
  {
    title: "Changes to This Privacy Policy",
    paragraphs: [
      "We may update this Privacy Policy when our website, data practices, or legal obligations change. The effective date and last updated date at the top of this page will indicate when the current version took effect. Material changes will be presented through the website or another appropriate communication channel where required.",
    ],
  },
  {
    title: "Contact Us",
    paragraphs: [
      `For questions, access or correction requests, privacy concerns, or requests about information submitted through Solar Compare, contact ${companyName} at solarcompare.in@gmail.com. You may also write to us at E-29 Girnar Valley, Bhopal, Madhya Pradesh 462010, India. Please include enough detail for us to identify the relevant account or request, but do not send passwords or verification codes.`,
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-slate-50/70">
      <section className="border-b border-slate-200 bg-white">
        <div className="mx-auto max-w-7xl px-4 py-14 md:px-8 md:py-20">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-slate-500">Solar Compare</p>
          <h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-0.04em] text-slate-950 md:text-6xl">Privacy Policy</h1>
          <p className="mt-5 max-w-3xl text-base leading-8 text-slate-600 md:text-lg">
            How {companyName} handles information across the Solar Compare platform.
          </p>
          <div className="mt-8 flex flex-wrap gap-x-8 gap-y-3 text-sm font-medium text-slate-600">
            <span>Effective Date: 19 September 2026</span>
            <span>Last Updated: 19 September 2026</span>
          </div>
        </div>
      </section>

      <main className="mx-auto grid max-w-7xl gap-8 px-4 py-10 md:px-8 md:py-14 lg:grid-cols-[minmax(0,1fr)_18rem]">
        <article className="space-y-5">
          {sections.map((section) => (
            <section key={section.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_14px_36px_rgba(15,23,42,0.04)] md:p-8">
              <h2 className="text-xl font-semibold tracking-[-0.02em] text-slate-950 md:text-2xl">{section.title}</h2>
              <div className="mt-4 space-y-4 text-sm leading-7 text-slate-600 md:text-base">
                {section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
                {section.items ? (
                  <ul className="list-disc space-y-2 pl-5 marker:text-slate-400">
                    {section.items.map((item) => <li key={item}>{item}</li>)}
                  </ul>
                ) : null}
              </div>
            </section>
          ))}
        </article>

        <aside className="h-fit rounded-3xl border border-slate-200 bg-slate-950 p-6 text-white lg:sticky lg:top-28">
          <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-400">Policy summary</p>
          <p className="mt-4 text-lg font-semibold leading-7">Clear solar decisions begin with clear information practices.</p>
          <p className="mt-4 text-sm leading-7 text-slate-300">
            This policy describes the information used to provide accounts, comparisons, enquiries, vendor connections, calculators, notifications, and support.
          </p>
          <a href="mailto:solarcompare.in@gmail.com" className="mt-6 inline-flex text-sm font-semibold text-white underline decoration-slate-500 underline-offset-4 transition hover:decoration-white">
            Contact privacy support
          </a>
        </aside>
      </main>
    </div>
  );
}
